### ISSUE TITLE
看不懂😂能不能大致写一下怎么用？

### ISSUE THREAD

**Issue by nukewarrior** [vicnoah/vts#1]
看不懂😂能不能大致写一下怎么用？
😭

**Comment by vicnoah** [comment]
可以，但得等等，我没有将项目release需要release后才能用，否则你需要自己编译程序

**Comment by nukewarrior** [comment]
乖乖坐等😋

**Comment by vicnoah** [comment]
> 乖乖坐等

好了，基本用法已添加，程序可以从release中下载，建议使用linux环境，并有较新显卡。没有在windows测试过，windows可以自己将ffmpeg的gpu转码环境配置好，编辑好模板进行转码。
